version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.4.0"
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
    env_file:
      - .env
    ports:
      - "9200:9200"
      - "9300:9300"
